language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install

script:
  - find ./component -name '*.php' -exec php -l {} \;
  - php .travis/phpcs.php
  - ./vendor/bin/phpmd component/ text codesize,unusedcode,naming
